### ISSUE TITLE
Bugs: @raw2sqlalchemy (MiniConda + Travis-CI)

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#107]
## Bug description / Feature enhancement
<https://travis-ci.com/github/dns-test/domain-tester-004/jobs/378468673#L2416>

Exception: Unable to download `https://raw.githubusercontent.com/funilrys/[secure]/dev/.[secure]_production.yaml` (status code: 503).

## Modifications under `.PyFunceble.yaml`

<https://github.com/dns-test/script-hub/blob/master/.travis.yml.bak>

```yml
  - Pyfunceble_version: 'PyFunceble@raw2sqlalchemy'
  - PYFUNCEBLE_CONFIG_DIR: "${TRAVIS_BUILD_DIR}/.pyfunceble/"
  - PYFUNCEBLE_OUTPUT_LOCATION: "${TRAVIS_BUILD_DIR}/.pyfunceble/"
  - PYFUNCEBLE_AUTO_CONFIGURATION: yes
  - PYFUNCEBLE_DB_CHARSET="${DB_CHARSET}"
  - PYFUNCEBLE_DB_HOST="${DB_HOST}"
  - PYFUNCEBLE_DB_NAME="${DB_NAME}"
  - PYFUNCEBLE_DB_USERNAME="${DB_USERNAME}"
  - PYFUNCEBLE_DB_PASSWORD="${DB_PASSWORD}"
  - PYFUNCEBLE_DB_PORT="${DB_PORT}"
```

## Reproduction

1. Break access to external sources

## Expected behavior
In case, there are any errors getting **_any_** external contents, re-run same process 3 times with delays, to help the job to succeed, with a log output that says something like: `Retrying to to get: xxx`

## Screenshots
![image](https://user-images.githubusercontent.com/44526987/91551893-35945300-e92b-11ea-959b-517d2654dd43.png)

## Versions

**OS:** MiniConda + Travis-CI
**Python Version:** 3.8.5
**PyFunceble Version:** @raw2sqlalchemy (3.2.11.pre-dev)
