### ISSUE TITLE
Fatal Error: 'NoneType' object has no attribute 'tested_at'

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#195]
## Bug description
See title :arrow_double_up: 

## Modifications under `.PyFunceble.yaml`
```yml
debug:
  active: False
  level: info
cli_decoding:
  adblock_aggressive: False
  adblock: False
  rpz: False
  wildcard: False
cli_testing:
  hosts_ip: "0.0.0.0"
  max_workers: null
  autocontinue: False
  inactive_db: True
  whois_db: True
  complements: False
  cooldown_time: 0.0
  db_type: mariadb
  file_filter: null
  mining: False
  local_network: True
  ci:
    active: False
    commit_message: "PyFunceble - AutoSave"
    end_commit_message: "PyFunceble - Results"
    max_exec_minutes: 15
    branch: master
    distribution_branch: master
    command: null
    end_command: null
  display_mode:
    dots: False
    execution_time: True
    percentage: True
    quiet: False
    less: False
    all: True
    simple: False
    colour: True
    status: all
  testing_mode:
    availability: True
    syntax: False
    reputation: False
  days_between:
    db_clean: 28
    db_retest: 1
  sorting_mode:
    hierarchical: True
    standard: True
  file_generation:
    no_file: False
    hosts: False
    plain: True
    analytic: True
    unified_results: False
lookup:
  dns: True
  http_status_code: True
  netinfo: True
  special: True
  whois: True
  reputation: False
  timeout: 0
dns:
  server: 185.109.89.254 130.225.244.166 130.226.161.34 185.38.24.52 198.180.150.12 94.126.178.9 192.168.1.1 91.239.100.100 89.233.43.71 198.180.150.12 185.38.24.52 130.226.161.34 95.216.209.53 116.203.32.67 192.168.1.2 192.168.1.3 192.168.1.4 192.168.1.5 192.168.1.53
  protocol: UDP
share_logs: True
user_agent:
  browser: firefox
  platform: linux
  custom: null
verify_ssl_certificate: False
```

A clear representation of what you changed.

## Reproduction
```console
pyfunceble -f https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/submit_here/hosts.txt \ https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/submit_here/mobile.txt \
https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/submit_here/snuff.txt \
https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/submit_here/strict_adult.txt -w 15
```

## Screenshots
![image](https://user-images.githubusercontent.com/44526987/104731572-2e37df80-573c-11eb-98f1-d81bb868d82b.png)
![image](https://user-images.githubusercontent.com/44526987/104731591-37c14780-573c-11eb-9071-55832051d8c2.png)
![image](https://user-images.githubusercontent.com/44526987/104731615-414aaf80-573c-11eb-982a-e52169838e32.png)
![image](https://user-images.githubusercontent.com/44526987/104731651-51fb2580-573c-11eb-80be-bc6224cfb34a.png)
![image](https://user-images.githubusercontent.com/44526987/104731679-5aebf700-573c-11eb-9812-c7244ad58879.png)
![image](https://user-images.githubusercontent.com/44526987/104731706-65a68c00-573c-11eb-9a59-d1f7dbe4121e.png)
![image](https://user-images.githubusercontent.com/44526987/104731738-6f2ff400-573c-11eb-99cf-de499b5c8b7f.png)

## Versions

**OS:** Ubuntu 20.02 + virtualenv
**Python Version:** 3.9.1
**PyFunceble Version:** 773e5f9
