### ISSUE TITLE
.PyFunceble_production.yaml not updated in GHA

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#207]
## Bug description
It seems like `.PyFunceble_production.yaml` doesn't get updated as expected.. if test branch other than master

Same, commits are not pushed to test branch, but running purely on master branch seems to work...
  <https://github.com/dns-test/rpz.mypdns.cloud/commit/fe559fe60b6b561babc78113e6b299aa4a8b21df>

```yaml
cli_testing:
    autocontinue: true
    ci:
        active: true
        branch: test-run
```

## Modifications under `.PyFunceble.yaml`

https://github.com/dns-test/rpz.mypdns.cloud/blob/4baf36b337484b284af04bb2126212a16c9dfe2f/.pyfunceble/.pyfunceble-env

## Reproduction

https://github.com/dns-test/rpz.mypdns.cloud/runs/1757531036?check_suite_focus=true

https://github.com/dns-test/rpz.mypdns.cloud/blob/4baf36b337484b284af04bb2126212a16c9dfe2f/.github/workflows/main.yml

## Expected behavior
All `.pyfunceble/**` to be updated to match new `.yml`

## Versions

**OS:** GHA: ubuntu-latest
**Python Version:** 3.9.1
**PyFunceble Version:** PyFunceble 4.0.0b16.dev (Blue Duckling)

**Comment by spirillen** [comment]
```consule
git up
Fetching origin
Updating 4baf36b..fe559fe
Fast-forward
 .pyfunceble/.PyFunceble.yaml                 |  176 +--
 .pyfunceble/.pyfunceble_intern_downtime.json |   12 +-
 .pyfunceble/hashes_tracker.json              |   13 -
 .pyfunceble/iana-domains-db.json             |  169 +--
 .pyfunceble/inactive.csv                     |    3 +
 .pyfunceble/public-suffix.json               | 8082 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------------
 .pyfunceble/user_agents.json                 |   26 +-
 .pyfunceble/whois.csv                        |    5 +
 8 files changed, 4316 insertions(+), 4170 deletions(-)
 delete mode 100644 .pyfunceble/hashes_tracker.json
 create mode 100644 .pyfunceble/inactive.csv
 create mode 100644 .pyfunceble/whois.csv

```

**Comment by funilrys** [comment]
Just a clarification @spirillen, are you talking about `.PyFunceble.yaml`? 

I'm asking because `.PyFunceble_production.yaml` is not updated nor needed anymore.

**Comment by spirillen** [comment]
I'll get back to this one, as I for this moment don't recall the entire situation...

**Comment by funilrys** [comment]
PyFunceble will read 2 configuration file.

1. The one it comes with: `$installDIR/PyFunceble/data/infrastructure/.PyFunceble_production.yaml`
2. The one at your configuration location `$configDir/.PyFunceble.yaml`

(1) is only read when (2) is not found. But we don't copy (1) into `$configDir/.PyFunceble_production.yaml`. 

In the past (1) was only remote accessible and downloaded to this repository and installed as `$configDir/.PyFunceble_production.yaml`. 

Therefore, we don't need it anymore.

**Comment by spirillen** [comment]
To get back to this issue.

The situation was, I was lunching from `$configDir/.PyFunceble.yaml@v3` to `$configDir/.PyFunceble.yaml@v4` 

And the `$configDir/.PyFunceble.yaml` wasn't updated **on sub-branch** as I would expect.

The real issue seems to be, that @PyFunceble are not able to run on a sub-branch.... and in fact have very little to do with the `$installDIR/PyFunceble/data/infrastructure/.PyFunceble_production.yaml` aka `$configDir/.PyFunceble.yaml`

I'm sorry for the confusion, for as I recall it, I was originally believing the yaml wasn't updated, and then, I should have change the context of the issue, but somehow forgotten to follow up on it.

The real bug is in 

```yaml
cli_testing:
    autocontinue: true
    ci:
        active: false
        branch: !=master
        command: ''
        commit_message: My Privacy DNS Firewall - AutoSave
        distribution_branch: master
        end_command: ''
        end_commit_message: My Privacy DNS Firewall - Results [GHA SKIP]
        max_exec_minutes: 45
```
