### ISSUE TITLE
BUG: Memory Leak + processes are not stopped + m*Sql retry

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#263]
## Description

Extremely high consumption of memory, See screenshot

MySql connection keeps breaking, there should be a retry 3 times (with delay), before failing. the reasons for a broken connection can be many.

## Configuration
```yml
cli_testing:
  cidr_expand: true
  db_type: mariadb
  display_mode:
    all: true
    colour: true
    dots: false
    execution_time: true
    less: false
    percentage: true
    quiet: false
    simple: false
    status: all
  file_generation:
    analytic: true
    hosts: false
    merge_output_dirs: false
    no_file: false
    plain: true
    unified_results: false
  local_network: true
  sorting_mode:
    hierarchical: true
debug:
  active: true
  level: critical
lookup:
  dns: true
  http_status_code: true
  netinfo: true
  reputation: false
  special: true
  timeout: 5
  whois: true
user_agent:
  browser: firefox
  custom: null
  platform: linux
dns:
  follow_server_order: false
  trust_server: false
  protocol: UDP
  server:
    - 130.226.161.34
    - 89.233.43.71
    - 185.121.177.177
    - 163.172.168.171
    - 192.168.1.100:5302
    - 192.168.1.6
collection:
   push: true
   url_base: <snip>
```

## Reproduction

Any bigger zone file to test

`pyfunceble -w 60 --rpz -f /tmp/pyfunceble/rpz.mypdns.cloud`

## Expected behavior

No error and all pyfunceble threads to disappear.

## Screenshots

![image](https://user-images.githubusercontent.com/44526987/137891846-dc4d3ebe-4e1f-4bdd-b2ba-465f671adffd.png)

![image](https://user-images.githubusercontent.com/44526987/137886824-c9bd0e67-74a8-4079-b415-92e8aa98199d.png)

![image](https://user-images.githubusercontent.com/44526987/137886911-1599274b-fe2f-4433-99df-f46ccd6d76fb.png)

## Versions

**OS:** Ubuntu 20.04

**Python Version:** 3.9.5

**PyFunceble Version:** 4.0.2b1.dev
