### ISSUE TITLE
BUG: Weird output in ACTIVE/list

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#275]
## Description
Seems like I forgot to read a later RFC for valid DNS syntax... :smirk: :smiling_face_with_tear: 

Non the less I found these in my `output/domain/ACTIVE/list`
```
functionalclam.com (UnResponSive)

..SNIP..

ga87z2o.com (Temporarily Down for Maintenance.)
```

## Configuration
<details><summary>.PyFunceble.overwrite.yaml</summary>

```yml
cli_testing:
  autocontinue: true
  cidr_expand: true
  db_type: mariadb
  display_mode:
    all: true
    colour: true
    dots: false
    execution_time: true
    less: false
    percentage: true
    quiet: false
    simple: false
    status: all
  file_generation:
    analytic: true
    hosts: false
    merge_output_dirs: false
    no_file: false
    plain: true
    unified_results: false
  local_network: true
  sorting_mode:
    hierarchical: true
debug:
  active: true
  level: critical
lookup:
  collection: true
  dns: true
  http_status_code: true
  netinfo: true
  reputation: false
  special: true
  timeout: 5
  whois: true
user_agent:
  browser: firefox
  custom: null
  platform: linux
dns:
  follow_server_order: false
  trust_server: false
  protocol: UDP
  server:
    - 130.226.161.34
    - 89.233.43.71
    - 185.121.177.177
    - 163.172.168.171
    - "127.0.0.1:5302"
    - 192.168.1.6
collection:
   preferred_status_origin: recommended
   push: true
   url_base: https://collection.dead-hosts.funilrys.com
```

</details>

## Reproduction
1. pyfunceble -f ../live.txt (https://mypdns.org/-/snippets/42)
2. take a peek into the list (requires of curse the NIC is down :joy: 

## Versions

**OS:** Ubuntu 20,04

**Python Version:** 3.10

**PyFunceble Version:** 4.0.1

## Additional context
Thanks good I did not just copy/paste this one into production...
