### ISSUE TITLE
BUG: dead-hosts keeps pulling configuration error Action

### ISSUE THREAD

**Issue by bigdargon** [funilrys/PyFunceble#314]
## Description

The configuration file in the editing library adds new lines, causing the Action to fail

https://github.com/dead-hosts/template/commit/6d7abb0b31648cb33d3673c35b87a6bdae2b4f94

```
https: null
    rules: []
share_logs: false
user_agent:
    browser: chrome
    custom: null
    platform: linux
verify_ssl_certificate: false
```

In the previous comment I mentioned https://github.com/funilrys/PyFunceble/issues/299#issuecomment-1196221039, but after fixing, only 1 line A was removed, the remaining lines were still added.

I think, dead-hosts after running the Action pulled themselves PyFunceble's default configuration to override the dead-hosts' Action. But for some reason, the default configuration end was appended with malformed configuration lines, causing the Action to fail.

Thanks again for your project!
