### ISSUE TITLE
BUG: Dead-hosts run continuously without completing

### ISSUE THREAD

**Issue by bigdargon** [funilrys/PyFunceble#325]
## Description

After a few days of running Dead-hosts, it seems to me that with a large number of domains (more than 17,000 domains) there will be some problems:

1. [hostsVN-dead-hosts](https://github.com/bigdargon/hostsVN-dead-hosts) repeats from the beginning of list but does not continue to other domains when running a new Action. The counter is more than 150,000 domains [link](https://github.com/bigdargon/hostsVN-dead-hosts/blob/master/output/origin.list/counter.json), while the list is only about 17,000 domains [link](https://github.com/bigdargon/hostsVN-dead-hosts/blob/master/origin.list)
2. [hostsVN-gambling-dead-hosts](https://github.com/bigdargon/hostsVN-gambling-dead-hosts) still runs the Action, doesn't repeat but doesn't seem to continue working. The list has more than 21,500 domains [link](https://github.com/bigdargon/hostsVN-gambling-dead-hosts/blob/master/origin.list), but currently stops at 18,000 domains [link](https://github.com/bigdargon/hostsVN-gambling-dead-hosts/blob/master/output/origin.list/counter.json), the domain will continue when the upstream updates more new domains (ex: https://github.com/bigdargon/hostsVN-gambling-dead-hosts/commit/179a448901561b2a651033ab0a5a7651b5d18256)

- Updated: There are over 75,000 domains. Dead-hosts Action runs without end

3. [hostsVN-adult-dead-hosts](https://github.com/bigdargon/hostsVN-adult-dead-hosts) list has more than 12,000 domains [link](https://github.com/bigdargon/hostsVN-adult-dead-hosts/blob/master/origin.list), running Actions without repeating errors like the 2 repos above.

- Updated: There are over 19,000 domains. Dead-hosts Action runs without end

It seems that the number of test domains will decrease over time when running Action. The longer the Action runs, the fewer domains are checked.
Repo hostsVN-gambling-dead-hosts: https://github.com/bigdargon/hostsVN-gambling-dead-hosts/commits/master/output/origin.list/counter.json
Repo hostsVN-adult-dead-hosts: https://github.com/bigdargon/hostsVN-adult-dead-hosts/commits/master/output/origin.list/counter.json

## Configuration

```
cli_testing:
    autocontinue: true
    chancy_tester: true
    ci:
        active: true
        branch: master
        command: hash dead_hosts_launcher && dead_hosts_launcher --save
        commit_message: '[Autosave][Dead-Hosts::hostsVN-dead-hosts]'
        distribution_branch: master
        end_command: hash dead_hosts_launcher && dead_hosts_launcher --end
        end_commit_message: '[Final/Result][Dead-Hosts::hostsVN-dead-hosts]'
        max_exec_minutes: 20
    cooldown_time: 0.2
    display_mode:
        all: true
        dots: true
        execution_time: true
        less: false
    max_workers: 5
dns:
    server:
    - 45.90.28.0
    - 45.90.30.0
lookup:
    collection: false
```
