### ISSUE TITLE
BUG | result and results (output file) do not match

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#393]
### What is the problem you are experiencing?

I am experiencing a problem where the test and it output files do not match, see screenshot where the number of inactive do not match the shown test results...

### How can we reproduce the problem?

To reproduce the problem:

1. `rm -fr ~/pyfunceble/ && pyfunceble -c --preload --all --execution --hierarchical -f https://raw.githubusercontent.com/mypdns/matrix/refs/heads/master/source/redirector/domains.list`

### Do you have a screenshot?

<details><summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/6613d786-ae87-4671-b484-7cc0432627fe)

</details>

### What did you expect to happen?

The tested results would be in the output folder and not lost somewhere....

### Is there a workaround?

Nope

### How did you configure PyFunceble?

```yaml
cli_testing:
  #db_type: mariadb
  inactive_db: yes
  whois_db: yes
lookup:
  dns: yes
  http_status_code: yes
  netinfo: yes
  special: yes
  whois: yes
  reputation: no
  platform: yes
  timeout: 2
dns:
  follow_server_order: no
  trust_server: yes
  server:
    - 9.9.9.10
    - 149.112.112.10
  protocol: UDP
  delay: 0.0

#proxy:
#  rules:
#    - http: socks5h://192.168.1.5:9050
#      https: socks5h://192.168.1.4:9050
#      tld:
#        - onion
#  global:
#    http: socks5h://192.168.1.1:9050
#    https: socks5h://192.168.1.1:9050
verify_ssl_certificate: no
max_http_retries: 2

platform:
  push: yes
  preferred_status_origin: recommended
  checker_priority:
    - availability
    - syntax
  checker_exclude:
    - reputation

```

### Which Operating System did you use?

Ubuntu 22.04 LTS

### Which Python Version did you use?

3.11

### Which PyFunceble Version did you use?

4.3.0a5.dev

### Additional context

I also experience the complete lack of any output files at all
