### ISSUE TITLE
BUG | unable to change `no-files` value

### ISSUE THREAD

**Issue by spirillen** [funilrys/PyFunceble#406]
### What is the problem you are experiencing?

In the latest dev version, I'm unable to change the value for `--no-files` either by config script or CLI

### How can we reproduce the problem?

To reproduce the problem:

1. Any CLI command 

### Do you have a screenshot?

<details><summary>Screenshot</summary>

![image](https://github.com/user-attachments/assets/f27e2a8b-c795-4a00-9b73-609d6c9e2ada)

![image](https://github.com/user-attachments/assets/7fb9e58c-30f1-41d7-9e0b-0dba96e75247)

`.PyFunceble.overwrite.yaml`  

![image](https://github.com/user-attachments/assets/acbe6de8-69cf-4a6b-ac3a-3f4ca3b568b9)

</details>

### What did you expect to happen?

File (IN)ACTIVE got generated at the end

### Is there a workaround?

**_NOPE_**

### How did you configure PyFunceble?

```yaml
.PyFunceble.overwrite.yaml

cli_testing:
  autocontinue: no
  inactive_db: no
  db_type: mariadb
  display_mode:
    execution_time: yes
    all: yes
    colour: no
  testing_mode:
    platform_contribution: yes
  sorting_mode:
    hierarchical: yes
  file_generation:
    analytic: no
    no_file: no

dns:
  follow_server_order: no
  trust_server: yes
  server:
    - 127.0.0.1

proxy:
  # global:
  #   http: http://$HOST:8080
  #   https: http://$HOST:8080
  rules:
    - http: socks5h://$HOST:9050
      https: socks5h://$HOST:9050
      tld:
        - onion

platform:
  push: yes
  checker_priority:
    - availability
    - syntax
  checker_exclude:
    - reputation

```

```yaml
.PyFunceble.yaml

cli_decoding:
    adblock: false
    aggressive: false
    rpz: false
    wildcard: false
cli_testing:
    autocontinue: false
    chancy_tester: false
    ci:
        active: false
        branch: master
        command: null
        commit_message: PyFunceble - AutoSave
        distribution_branch: master
        end_command: null
        end_commit_message: PyFunceble - Results
        max_exec_minutes: 15
    cidr_expand: false
    complements: false
    cooldown_time: 0.0
    days_between:
        db_clean: 28
        db_retest: 1
    db_type: csv
    display_mode:
        all: false
        colour: true
        dots: false
        execution_time: false
        less: true
        max_registrar: 15
        percentage: true
        quiet: false
        registrar: false
        simple: false
        status: all
    file_filter: null
    file_generation:
        analytic: true
        hosts: false
        merge_output_dirs: false
        no_file: false
        plain: true
        unified_results: false
    hosts_ip: 0.0.0.0
    inactive_db: true
    local_network: false
    max_workers: null
    mining: false
    preload_file: false
    sorting_mode:
        hierarchical: false
        standard: true
    testing_mode:
        availability: true
        platform_contribution: false
        reputation: false
        syntax: false
    whois_db: true
debug:
    active: false
    level: info
dns:
    delay: 0.0
    follow_server_order: true
    protocol: UDP
    server: null
    trust_server: false
http_codes:
    list:
        potentially_down:
        - 400
        - 402
        - 404
        - 409
        - 410
        - 412
        - 414
        - 415
        - 416
        - 451
        potentially_up:
        - 0
        - 300
        - 301
        - 302
        - 303
        - 304
        - 305
        - 307
        - 308
        - 403
        - 405
        - 406
        - 407
        - 408
        - 411
        - 413
        - 417
        - 418
        - 421
        - 422
        - 423
        - 424
        - 426
        - 428
        - 431
        - 500
        - 501
        - 502
        - 503
        - 504
        - 505
        - 506
        - 507
        - 508
        - 510
        - 511
        up:
        - 100
        - 101
        - 102
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
        - 207
        - 208
        - 226
        - 429
    self_managed: false
links: {}
lookup:
    dns: true
    http_status_code: true
    netinfo: true
    platform: false
    reputation: false
    special: true
    timeout: 5
    whois: true
max_http_retries: 3
platform:
    checker_exclude:
    - none
    checker_priority:
    - none
    preferred_status_origin: recommended
    push: false
proxy:
    global:
        http: null
        https: null
    rules: []
share_logs: false
user_agent:
    browser: chrome
    custom: null
    platform: linux
verify_ssl_certificate: false

```

### Which Operating System did you use?

Debian 12, Ubuntu 24.04 LTS, Unix or *BSD like OS

### Which PyFunceble Version did you use?

4.3.0a9.dev
